In [1]:
import tensorflow

In [13]:
import numpy as np
np.rot90([
    [1,2]
],1,(0,1))

array([[2],
       [1]])

In [16]:
m = np.arange(8).reshape((2,2,2))

In [19]:
np.rot90(m,1)

array([[[2, 3],
        [6, 7]],

       [[0, 1],
        [4, 5]]])

In [25]:
m.reshape(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [24]:
# The array is rotated in the plane defined by the axes. Axes must be different.
# rot90的结果是内积为0？？ 不太对？？

np.rot90(m,2,axes=(1,2))

array([[[3, 2],
        [1, 0]],

       [[7, 6],
        [5, 4]]])

In [23]:
m

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [27]:
from tensorflow.keras.layers import Convolution2D

In [31]:
for idx, p in enumerate([1,2]):
    print(idx, p)

0 1
1 2


In [34]:
np.random.dirichlet(np.full(10,0.01))

array([9.99958064e-001, 1.35608594e-055, 4.16884991e-119, 1.36905126e-049,
       4.78826577e-043, 6.71145105e-015, 8.82821843e-010, 4.19348636e-005,
       1.61180222e-016, 5.37828951e-010])

array([0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01])